services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=todaybread'
      - 'MYSQL_USER=todaybread'
      - 'MYSQL_PASSWORD=todaybread'
      - 'MYSQL_ROOT_PASSWORD=rootpassword'
    ports:
      - '3306:3306'