spring.application.name=server

# OPEN API SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.todaybread.server
springdoc.paths-to-match=/api/**

# ============================================================
# DataSource (MySQL)
# Database setting could be load from your .env file.
# needs to load MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD
# if there is no setting .env file, it will load up with default setting.
# default settings are the values next to variable name
# ex) MYSQL_USER:todaybread -> this means, it will load .env file if there is value in there, if isn't, it will load it as todaybread.
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE:todaybread}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${MYSQL_USER:todaybread}
spring.datasource.password=${MYSQL_PASSWORD:todaybread}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================================
# JPA / Hibernate
# Schema exchange is guaranteed by FLYWAY only.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ============================================================
# Hikari config
# it isn't really important at this moment, we can tune db once it gets bigger.